### ISSUE TITLE
The Y position takes size of the screen ? 

### ISSUE THREAD

**Issue by keshavSahu-27** [full-fledged/alerts#1]
![image](https://user-images.githubusercontent.com/63944285/102685554-98299b80-4207-11eb-9d92-dccf2935e506.png)
Why this is happening, previously I have used ngx-alerts too andit worked fine but after this update I am unable to use this.Please help me.

**Comment by MathijsBlok** [comment]
Hi, are you using the <ff-alerts></ff-alerts> component in your app component, and not in a different container?
Also, which angular version are you using.

You can check out this project and run it with npm run start, in this example project the sizing is working as it should

**Comment by keshavSahu-27** [comment]
@MathijsBlok , thanks for reply.  I am using angular version 10.1.5. and also Actually I have used router-outlet in my app component and the component on which I have used your  component  is loading in app component.

**Comment by MathijsBlok** [comment]
Can you maybe try to use  https://www.npmjs.com/package/ngx-alerts (version 10.1.3) and let me know if that works for you? This new repository is used with angular 11.

**Comment by keshavSahu-27** [comment]
@MathijsBlok Thank you, it resolved my issue.
