### ISSUE TITLE
Angular minimum version

### ISSUE THREAD

**Issue by jonaaix** [full-fledged/alerts#2]
Hi, I am currently using the old library `ngx-alerts` and I always need to install npm with `--legacy-peer-deps`. Yarn doesn't even work at all.
In this new version, the minimum Angular version is set to 12.0, is there any reason for it? Because I am still on 11.2 and can't use it...
The correct way to set the peer dependencies without breaking future versions is this:

```json
   "peerDependencies": {
      "@angular/common": ">=6.0.0",
      "@angular/core": ">=6.0.0",
      "@angular/platform-browser": ">=6.0.0",
      "rxjs": ">=6.0.0"
   }
```
Afaik Angular 6.0 had the last breaking changes against Libraries, so there shouldn't be a problem setting this to 6 or 8.

**Comment by MathijsBlok** [comment]
Hi, i just synced the versions with the angular version. I had an issue with the some changes between angular 10 and 11 i believe so that's why i keep them on the same version now. 

You should probably be able to use version 11.0.2 (npm i --save @full-fledged/alerts@11.0.2) if you're on angular 11

**Comment by jonaaix** [comment]
@MathijsBlok thanks, I'll test it

**Comment by jonaaix** [comment]
I could upgrade to Angular 12 today, so it doesn't matter anymore
